[package]
name = "day_10"
version = "0.1.0"
authors = ["Bernatsky Pavel <pasha.desh@yandex.by>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
